# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45f95519095e6bb58772db60ff2198b98a39b291585a04d4c5e58055f0e8bb25e15da12f070cfd500e7c5837a5316420049dc838d2792f4491bffb3f60e48f6d

test:
  secret_key_base: 4eb52035869631f1fcb94fa5ca9078dfd24c4d63f8ed9a76c945ee5843732b5bf167a8ed41f3103d32a06e3a2e1636115f81fb8f4a78b73a07227bec64386070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
